//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMXH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALL
    {
        public int IDCALL { get; set; }
        public Nullable<System.DateTime> THOIGIAN_BD { get; set; }
        public Nullable<System.DateTime> THOIGIAN_KT { get; set; }
        public Nullable<System.DateTime> THOILUONG { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> IDGROUP { get; set; }
    
        public virtual GROUP GROUP { get; set; }
        public virtual USERR USERR { get; set; }
    }
}
