//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMXH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE
    {
        public int IDMES { get; set; }
        public Nullable<int> FROM_USER { get; set; }
        public Nullable<int> TO_USER { get; set; }
        public string MESSAGE1 { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
