//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMXH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MXH_GREENZONEEntities : DbContext
    {
        public MXH_GREENZONEEntities()
            : base("name=MXH_GREENZONEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAIVIET> BAIVIET { get; set; }
        public virtual DbSet<BANBE> BANBE { get; set; }
        public virtual DbSet<CALL> CALL { get; set; }
        public virtual DbSet<COMMENT> COMMENT { get; set; }
        public virtual DbSet<GROUPS> GROUPS { get; set; }
        public virtual DbSet<MESSAGE> MESSAGE { get; set; }
        public virtual DbSet<MESSAGE_PHONGHOP> MESSAGE_PHONGHOP { get; set; }
        public virtual DbSet<PHONGHOP> PHONGHOP { get; set; }
        public virtual DbSet<THICH> THICH { get; set; }
        public virtual DbSet<USER_CONNECTION> USER_CONNECTION { get; set; }
        public virtual DbSet<USER_TGHOP> USER_TGHOP { get; set; }
        public virtual DbSet<USERR> USERR { get; set; }
        public virtual DbSet<VIDEO_CUOCHOP> VIDEO_CUOCHOP { get; set; }
    }
}
