//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMXH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_CONNECTION
    {
        public int IDMES { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<System.Guid> CONNECTIONID { get; set; }
    
        public virtual USERR USERR { get; set; }
    }
}
