//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMXH.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USERR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERR()
        {
            this.BAIVIETs = new HashSet<BAIVIET>();
            this.CALLs = new HashSet<CALL>();
            this.COMMENTs = new HashSet<COMMENT>();
            this.GROUPS = new HashSet<GROUP>();
            this.MESSAGE_PHONGHOP = new HashSet<MESSAGE_PHONGHOP>();
            this.PHONGHOPs = new HashSet<PHONGHOP>();
            this.THICHes = new HashSet<THICH>();
            this.USER_CONNECTION = new HashSet<USER_CONNECTION>();
            this.USER_TGHOP = new HashSet<USER_TGHOP>();
            this.VIDEO_CUOCHOP = new HashSet<VIDEO_CUOCHOP>();
            this.BAIVIETs1 = new HashSet<BAIVIET>();
            this.GROUPS1 = new HashSet<GROUP>();
        }
    
        public int USERID { get; set; }
        [Required(ErrorMessage = "Tên đăng nhập không được để trống")]
        public string USERNAME { get; set; }
        [Required(ErrorMessage = "Họ và tên không được để trống")]
        public string FULLNAME { get; set; }

        [DataType(DataType.Password)]
        public string PASSWORD { get; set; }

        [Required(ErrorMessage = "Số diện thoại không được để trống")]
        public string SDT { get; set; }
        [Required(ErrorMessage = "Email không được để trống")]
        public string EMAIL { get; set; }
        public string HINHANH { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public Nullable<int> IDTOKEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIVIET> BAIVIETs { get; set; }
        public virtual BANBE BANBE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALL> CALLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUP> GROUPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MESSAGE_PHONGHOP> MESSAGE_PHONGHOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONGHOP> PHONGHOPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THICH> THICHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_CONNECTION> USER_CONNECTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_TGHOP> USER_TGHOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIDEO_CUOCHOP> VIDEO_CUOCHOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIVIET> BAIVIETs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUP> GROUPS1 { get; set; }
    }
}
