//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMXH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_TGHOP
    {
        public int IDPHONGHOP { get; set; }
        public int USERID { get; set; }
        public Nullable<bool> TRANGTHAI_MIC { get; set; }
        public Nullable<bool> TRANGTHAI_CAMERA { get; set; }
    
        public virtual PHONGHOP PHONGHOP { get; set; }
        public virtual USERR USERR { get; set; }
    }
}
